disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
line_length:
 warning: 250
 error: 400
 ignores_comments: true
 ignores_urls: true
 ignores_function_declarations: true
 ### works up until this config rule
 ignores_interpolated_strings: true
file_length:
 warning: 1000
 error: 2000
identifier_name:
 excluded: # excluded via string array
  - id
