//
//  TRPRecommendationInfoJsonModel.swift
//  TRPRestKit
//
//  Created by Evren Yaşar on 21.05.2018.
//  Copyright © 2018 Evren Yaşar. All rights reserved.
//

import Foundation

/// Indicates a poi that was generated by R.E.
public struct TRPRecommendationInfoJsonModel: Decodable {
    
    /// An Int value. Unique id of poi.
    public var poiRef: TRPPoiRefInfoModel
    public var score: Double
    /// Tag matcher
    private enum CodingKeys: String, CodingKey {
        case poiRef = "poiRef"
        case score
    }
    
    /// Json to Object converter
    ///
    /// - Parameter decoder: Json Decoder Object
    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        self.poiRef = try values.decode(TRPPoiRefInfoModel.self, forKey: .poiRef)
        self.score = try values.decode(Double.self, forKey: .score)
    }
}
